# Generated by Django 5.0.3 on 2024-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('position', models.CharField()),
                ('weight', models.PositiveIntegerField()),
                ('height', models.CharField()),
                ('college', models.CharField()),
            ],
        ),
    ]
