# Generated by Django 5.0.3 on 2024-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='years_pro',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
