# Generated by Django 5.0.3 on 2024-04-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='player_app.player')),
            ],
        ),
    ]
