# Generated by Django 5.0.3 on 2024-04-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_app', '0001_initial'),
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='player_app.player')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff_app.staff')),
            ],
        ),
    ]
